### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#104]
Hello! I made a logo for signalserver because it was looking a little sad without one.

<img width="508" alt="screen shot 2016-12-24 at 17 34 47" src="https://cloud.githubusercontent.com/assets/3260492/21513925/56ebff36-cc8c-11e6-87a4-c3a92969fc45.png">

**Comment by ablwr** [comment]
But I don't know where to put it?

**Comment by kieranjol** [comment]
Very nice logo!

**Comment by dericed** [comment]
Looks good.
I don't think there's any directory yet for ui resources. Feel welcome to make one. Do you have a higher resolution image for the logo, it looks a bit scaled, especially on the curved edges.

**Comment by ablwr** [comment]
Yeah, plus github compresses.This was a screenshot so it was not feeling its freshest. I can make a folder and upload original. hi-rez, scaled, etc.

**Comment by yayoiukai** [comment]
there is a folder for static files. I don't have holder for img but you can make one and you put it there?

**Comment by yayoiukai** [comment]
yay logo!
