### ISSUE TITLE
support/document programmatic method to upload qctools reports

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#11]
I'm not sure if this is currently possible, if so let's document it, if not let's implement it.

**Comment by dericed** [comment]
See related issue https://github.com/bavc/signalserver/issues/13 which will create a mockup for this

**Comment by yayoiukai** [comment]
can you explain to me a bit more?

**Comment by dericed** [comment]
The QCTools app needs to integrate a feature to send gzipped qctools xml data into signalserver. I presume that the QCTools app would need a url, username, and password and then could push a gzipped xml file into SignalServer, but SignalServer needs to be setup for uploads without requiring the web ui.

**Comment by yayoiukai** [comment]
API made.
