### ISSUE TITLE
extra base.html file

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#119]
Hey @yayoiukai 

I see fileuploads/templates/base.html and it doesn't seem to be called anywhere -- seems to be the same as the higher-level base.html. Can I remove it?

**Comment by yayoiukai** [comment]
yes you can!

**Comment by ablwr** [comment]
Great! I have a branch that is changing the frontend around so I will do it in that branch.

**Comment by yayoiukai** [comment]
cool

**Comment by ablwr** [comment]
Merge of #123 will resolve this, closing early!
