### ISSUE TITLE
policy buttons

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#136]
The buttons on the Policy page are a little wonky. There are two rename buttons, and they surround the rename field in an odd way. But I'm thinking it's better to just list the policies and their descriptions with an edit button. When they click through to edit, then they can rename, reset, or delete. Kinda like:

Dancing Banana |                    Flags files with high BRNG metrics |                  **edit**    
Dave's Party House |              Flags files with high saturation levels |              **edit**             
Kelly's TOUT Obsession |       Self-explanatory |                                                 **edit**    

And maybe also include a dropdown menu of all the groups so 

Dancing Banana |                  Flags files with high BRNG metrics |          **edit**    | **group to process**

Thoughts? Bueller?

**Comment by metacynicv2** [comment]
Also, if we list them we should have sorting capabilities?

**Comment by metacynicv2** [comment]
What the Policy page looks like on Amazon and the localhost version are very different, so I'm back to being a little confused by which version we should be sending issues regarding.

**Comment by ablwr** [comment]
Probably localhost because it is the most up-to-date. On localhost, the edit and delete should be at the top, near the rule #, and shaped like little buttons.

**Comment by ablwr** [comment]
I agree with this. I can make these changes. Can you give me a screenshot of what you mean with the double-rename buttons?

**Comment by metacynicv2** [comment]
This is what I see on localhost. git pull origin master reports it is up to date

<img width="343" alt="screen shot 2017-01-13 at 4 23 11 pm" src="https://cloud.githubusercontent.com/assets/9436241/21950120/bfcc5aa0-d9ac-11e6-926e-396fcf80e919.png">

**Comment by ablwr** [comment]
Weird! Anyway I will will rescind these links in lieu of just "edit" (or leave editing to the policy's page).

**Comment by yayoiukai** [comment]
ya the latest one is local. I will move the rename to edit page. (Having rename on the page was request from Dave. I assume that he would be okay with the change) And it seems for the above one, somehow javascript is not working correctly.. I will check that as well.. (Though rename move to edit, it doesn't matter..)

**Comment by ablwr** [comment]
I defer to @yayoiukai !

**Comment by metacynicv2** [comment]
Maybe @dericed should have ux fisticuffs?

**Comment by ablwr** [comment]
I did this
