### ISSUE TITLE
click through file names on group report and go to individual file report 

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#139]

**Comment by yayoiukai** [comment]
ya i remember that we talked about that. I will make a change.

**Comment by ablwr** [comment]
Does each file have its own page even if it hasn't been processed yet?

**Comment by ablwr** [comment]
Files seem to be loaded dynamically via a function wrapped into the get_graph route

**Comment by ablwr** [comment]
Tagging as 'backend' just because I need an endpoint showcased to work with

**Comment by yayoiukai** [comment]
I added it. I realized that there is a bit of an issue that how we want to handle the data but we can talk about that more.

**Comment by yayoiukai** [comment]
Well also it is there now, so please let me know what you think of it. Thank you!

**Comment by ablwr** [comment]
This was added? What is the endpoint and how to access for each file report?

**Comment by yayoiukai** [comment]
I added it to group process result page. So if you go to group result page, if there is a file result corresponding to that file or policy, there is a link and it will navigate to file result.
