### ISSUE TITLE
create group at point of upload

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#142]
creating a group is a multi-step process: upload individual files, search for individual files that you just uploaded, create group

suggesting a more simplified approach: 

choose to upload either a directory or individual files (as in MediaConch) 
at the prompt, choose if you want to create a new group or add to an existing group

possibly the name of the directory can default as the new group name

**Comment by dericed** [comment]
perhaps all uploads should belong dynamically to some default groups like `Reports-YYYY-MM-DD`.

**Comment by yayoiukai** [comment]
sure i will add something on upload page..(probably create new group and select group drop down menu or something..).

**Comment by yayoiukai** [comment]
I added the group creation and group selection on file listing page when you upload the files. Please let me know what you think of it. I will make automatic ones as well.  (Right now there is no create automatically option in group selection but I will add one)

**Comment by yayoiukai** [comment]
I added the group creation when you upload the files. It's been there for a while and no comment. So I close this one for now.

**Comment by dericed** [comment]
I've seen the group creation by upload and think it's really helpful. Although I wonder if the number of groups would be overwhelming if signalserver is used for a long time. Could we have a setting to enable/disable the feature?
