### ISSUE TITLE
More than one upload of same XML throws error

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#15]
It returns...

"MultipleObjectsReturned at /videostorage/list/show/test.mkv.qctools
get() returned more than one Video -- it returned 4!"

(etc etc etc)

**Comment by yayoiukai** [comment]
I just limited to one for now. But do you want to be able to add same file twice? Or Can I overwrite it? I can't keep them as both having the exact the same files name. I need to modify the file name itself if user needs to upload the same file names twice.

**Comment by ablwr** [comment]
Hmm... I guess overwriting is best with a prompt to the user that it already exists and will be overwritten? For now it doesn't matter much. I feel like in the future things will be loaded in as batches, and not one-at-a-time like now.

**Comment by yayoiukai** [comment]
Okay I will change it overwriting then.
