### ISSUE TITLE
add section on docker maintenance

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#150]
Suggest adding a section to readme on cleanup and maintenace of docker:

from debugging earlier we used.
```
docker ps -a -q | xargs docker rm -f
docker images -a -q | wc -l
docker images -a -q | xargs docker rmi -f
```

**Comment by yayoiukai** [comment]
Added the script and I will add the screen shots.

**Comment by yayoiukai** [comment]
![screen shot 2017-02-09 at 12 49 30 am](https://cloud.githubusercontent.com/assets/720709/22776921/6bd7e742-ee66-11e6-8eb9-e5072a4bb62e.png)
![screen shot 2017-02-09 at 12 49 54 am](https://cloud.githubusercontent.com/assets/720709/22776939/80c84282-ee66-11e6-9f6a-6d128af6ca06.png)

**Comment by yayoiukai** [comment]
Added script and image on Readme.
