### ISSUE TITLE
extra 'Rename' button on policy page

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#156]
On http://localhost:8000/policy/, each policy provides a text box to rename the policy and then there is a "Rename" button above that box which doesn't seem to do anything, and one rename button to the right of the text box which applies the rename.

**Comment by ablwr** [comment]
You should be seeing only one "rename" and when you click on it, you are able to rename on this page. The second "rename" causes it to happen and "reset" clears the box. I don't think we need "rename" on this page though and should be within the policy pages so I will move.
