### ISSUE TITLE
sometimes toolbar options don't dropdown

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#158]
I'm not certain in which cases this happens, but I still find instances where the dropdown lists for "Files" and "Account" don't actually drop down, which makes navigation a lot harder.

**Comment by dericed** [comment]
fixed by running ./frontend.sh and then ./quickstart.sh but I'm leaving this open since I think there is a typo about this process in the readme at https://github.com/bavc/signalserver/commit/2ad980070d08b0711f478689af8491eff3074fb0#commitcomment-20814113

**Comment by ablwr** [comment]
This is resolved in #160 although also keeping open since this seems to uncover a different issue regarding asset compilation

**Comment by yayoiukai** [comment]
Let's close it because if the issues are different, it should be handled on different issue.
