### ISSUE TITLE
Cannot add files to drop in Group Edit

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#171]
Tried to add files by dropping them into the area at the bottom of the page on http://192.168.99.100:8000/groups/update_group/ but nothing happened. I'm using Chrome.

**Comment by yayoiukai** [comment]
It means that somehow javascript is not loading. I will look.

**Comment by yayoiukai** [comment]
Well it looks like the same javascript loading issue. Also the change of the form structure was causing the issue.
