### ISSUE TITLE
file search button error

### ISSUE THREAD

**Issue by bealtaine84** [bavc/signalserver#179]
in the files page, when I click on the search button (having not filled out any search terms or search times), I get redirected to an error page that reads:

ValueError at /fileuploads/find_files/
time data '' does not match format '%Y/%m/%d %H:%M'
Request Method:	POST
Request URL:	http://localhost:8000/fileuploads/find_files/
Django Version:	1.10.5
Exception Type:	ValueError
Exception Value:	
time data '' does not match format '%Y/%m/%d %H:%M'
Exception Location:	/usr/local/lib/python3.4/_strptime.py in _strptime, line 344
Python Executable:	/usr/local/bin/python
Python Version:	3.4.5
Python Path:	
['/usr/src/app',
 '/usr/local/lib/python34.zip',
 '/usr/local/lib/python3.4',
 '/usr/local/lib/python3.4/plat-linux',
 '/usr/local/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/site-packages',
 '/usr/src/app']
Server time:	Tue, 14 Feb 2017 18:47:22 -0500

**Comment by ablwr** [comment]
Do you mean the `fileuploads/list/` page? I tried this and I am not having a problem with blank-search or search-terms search. Maybe it was fixed -- can you try it again?

**Comment by yayoiukai** [comment]
I am not having an issue too. I close it for now. If the issue persists, please let us know.
