### ISSUE TITLE
is 42 MB still the file size limit for qctools report?

### ISSUE THREAD

**Issue by bturkus** [bavc/signalserver#180]
or was the limit only for the AWS version of signalserver?

**Comment by JeromeMartinez** [comment]
There is no limit for QCTools reports.
Upload file size limit is a configuration value (from the web server, not AWS), and there is a balance to do between user experience (big value) and server security (low value).

**Comment by ablwr** [comment]
I don't even see in the code where the 42 MB rule is enforced. I think this is just to keep the AWS hosting load minimal because of the limited server size.

**Comment by ablwr** [comment]
I'm gonna rm the message and close this issue.
