### ISSUE TITLE
"files uploaded by you" create group error

### ISSUE THREAD

**Issue by bturkus** [bavc/signalserver#182]
when I click on "create group" from the files uploaded by you section (the green button), I get following error:

NameError at /fileuploads/search/
name 'user_name' is not defined

**Comment by bturkus** [comment]
update on this...I get the same error when I click on "Create New Group" in the Files drop down menu. I believe the only way to currently create a group is to "create_new" from the file upload menu.

One other problem: when I try to rename a group, I get the following error message

NoReverseMatch at /groups/update_group/
Reverse for 'edit_group' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['groups/edit_group/(?P<group_id>[0-9]+)$']

**Comment by ablwr** [comment]
This may be fixed now. It works for me. Can you re-test?

**Comment by yayoiukai** [comment]
It seems works for me too. I close it for now but please let us know if it is an issue.
