### ISSUE TITLE
front end script in readme.md yields error

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#191]
When I try to run this script from the README.md doc

`docker build -t signalserver-frontend  -f /Users/username/signalserver/Dockerfile-frontend
``
I get this error

> "docker build" requires exactly 1 argument(s).
> See 'docker build --help'.
> Usage:  docker build [OPTIONS] PATH | URL | -

Is the script incorrect?

**Comment by ablwr** [comment]
I believe it needs a . at the end of it...

`docker build -t signalserver-frontend -f /Users/username/signalserver/Dockerfile-frontend .`

**Comment by ablwr** [comment]
I thought there was a note about this from @dericed and it had been corrected?

**Comment by ablwr** [comment]
That worked so @kellyhaydon will update docs
