### ISSUE TITLE
policies: add new rule button doesn't add new rule

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#194]
On local version, when I click the "add new rule" button, nothing happens. I'm not sure if this is related to Docker installation or a true bug.

**Comment by ablwr** [comment]
This works for me. This and many of the other bugs seem to do with problems related to bower frontend assets not compiling properly.

**Comment by metacynicv2** [comment]
I shall close - no more testing until this front end thing is figure out O_O
