### ISSUE TITLE
graphs not building

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#196]
Seems that graphs are not generating, or only build sometimes when using the 'average' functionality and not more complex rules.

**Comment by metacynicv2** [comment]
<img width="1438" alt="screen shot 2017-03-05 at 4 38 26 pm" src="https://cloud.githubusercontent.com/assets/9436241/23593320/3de0662e-01c2-11e7-9893-e188131452bb.png">
Yep, we noticed this too when we were working today

**Comment by yayoiukai** [comment]
This error is telling that frontend assets are not loading. I changed the loading order for the javascript assets in base.html.. So it is building no problem for me.
