### ISSUE TITLE
Upload files directly into a group

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#204]
It would be handy to be able to upload files directly into the groups page. Right now you can only add files that were uploaded in another page. 

![screen shot 2017-03-19 at 11 28 05 am](https://cloud.githubusercontent.com/assets/9436241/24083604/4c637350-0c97-11e7-9bfb-13886dc2676f.png)

**Comment by yayoiukai** [comment]
Actually, you can upload directly into the group. There is a drop down list that you choose the group when you upload the file. Please let me know if it is not clear or not working very well.
