### ISSUE TITLE
Dashboard checkbox doesn't seem to do anything currently

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#210]
Just putting this here - seems the Dashboard checkbox isn't doing much.

**Comment by ablwr** [comment]
Cuz the dashboard isn't doing much, because it isn't developed yet! This is like a feature request... but it is on the roadmap.

**Comment by metacynicv2** [comment]
Can we remove the checkbox from the UI then?

**Comment by ablwr** [comment]
I think it's better to keep it for when the Dashboard magically exists!

**Comment by dericed** [comment]
+1 @ablwr
