### ISSUE TITLE
wishlist: bulk delete options

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#215]
deleting files one by one - would love to be able to delete them all at once

**Comment by yayoiukai** [comment]
like checklist or something? or you want to delete file all in the server?

**Comment by metacynicv2** [comment]
In my mind it would be great to be able to select files and then bulk
delete just those files. Or delete entire groups.

**Comment by yayoiukai** [comment]
sure. Do you want to delete the just content of the group or group itself along with the contents of the group?

**Comment by yayoiukai** [comment]
Added check and delete in the file list page and group delete (delete the group and entire files in the group from the server) in the group edit page. (I thought about adding group list page but I thought it may be too dangerous.) Please let me know what you think of it. Thank you.
