### ISSUE TITLE
Groups do not delete completely - only the name

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#217]
When I try to delete a group, only the name is deleted but the create time and policy remain in the "Your Groups" list

![screen shot 2017-04-02 at 3 38 27 pm](https://cloud.githubusercontent.com/assets/9436241/24591605/aecac646-17ba-11e7-9d11-9f3831c1211c.png)

**Comment by yayoiukai** [comment]
oh that's not good. I will take care of it.

**Comment by yayoiukai** [comment]
I moved the delete buttom to group list page (where you submit the process.) it delete group now.
