### ISSUE TITLE
How to request file process?

### ISSUE THREAD

**Issue by kieranjol** [bavc/signalserver#224]
I have yet to be able to process a file. I'm using chrome and Ubuntu 16.04. I raised an issue with using the Files->Process Files menu option here https://github.com/bavc/signalserver/issues/223

But I think I can also use fileuploads/list and use the 'Request File Process' button?
The 'frames processed' counter is always at zero for my uploads.
It seems like the 'show graph' and 'request file process' both link to signals/get_graph/
which shows something like this:
![request_file_process](https://cloud.githubusercontent.com/assets/1127102/25044479/c465a97c-211e-11e7-80ff-f9ea97635d9a.png)

**Comment by yayoiukai** [comment]
would you mind send me your file? It is possible that it is failing to read the file while processing. All QCtools files are slightly different depends on the base video format. It is possible that I need to account for this specific file format. So far I can process the files for the sample files I have.

**Comment by yayoiukai** [comment]
or you can post the sample file here.

**Comment by kieranjol** [comment]
[test2.zip](https://github.com/bavc/signalserver/files/924215/test2.zip)
Hi, this zip contains the video file (ffv1/mkv) and the qctools sidecar.

**Comment by yayoiukai** [comment]
Great thank you!

**Comment by yayoiukai** [comment]
I just pushed the bug fix. You should be able to process the files in the newest version. Thank you!
