### ISSUE TITLE
Fresh installation --  Creating volume "signalservertest_files" error

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#226]
Building fresh from the master branch, I get this error repeating infinitely --

```
Creating volume "signalservertest_dbdata" with default driver
Creating volume "signalservertest_files" with default driver
SystemCheckError: System check identified some issues:

ERRORS:
fileuploads.Video.videofile: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.
```

**Comment by ablwr** [comment]
This is from building with `FILES_VOLUME_PATH=/files ./quickstart.sh`. I also tried building with `FILES_VOLUME_PATH=files ./quickstart.sh` but get the same thing.

**Comment by iamdamosuzuki** [comment]
I'm having the same issue, and tried both of the commands mentioned above and got the same error.

**Comment by dericed** [comment]
Make sure you have permissions on /files.

**Comment by ablwr** [comment]
Even with 0777 `drwxrwxrwx`,  I still get the same error. I think this is related to the postgresql db building process.

**Comment by dericed** [comment]
I thought it might be an issue if `/files` was not listed in the "file sharing" preferences of Docker, however when I remove `/files` from docker's file sharing preferences my error doesn't match. I get (also repeating):

```
.
ERROR: Cannot start service web: Mounts denied: 
The path /files
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

I tried but was unable to recreate the issue.

**Comment by dericed** [comment]
OK some success. I ran:

```
docker ps -a -q | xargs docker rm -f
docker images -a -q | xargs docker rmi -f
```

to clean up and then re-ran `./quickstart.sh` and got the same error:

```
Status: Downloaded newer image for postgres:9.5
Creating signalserver_db_1
SystemCheckError: System check identified some issues:

ERRORS:
fileuploads.Video.videofile: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.
SystemCheckError: System check identified some issues:

ERRORS:
fileuploads.Video.videofile: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.
SystemCheckError: System check identified some issues:

ERRORS:
fileuploads.Video.videofile: (fields.E202) FileField's 'upload_to' argument must be a relative path, not an absolute path.
	HINT: Remove the leading slash.
^C
```

Will test for a regression from here.

**Comment by dericed** [comment]
Noting that I reset the variable in `.env` to a relative path (I'm not sure if .env normally takes precedent over a declared value on command line before quickstart or not), but get the same error regardless.

**Comment by dericed** [comment]
Updating with debug notes. The error arises from this function, https://github.com/django/django/blame/master/tests/invalid_models_tests/test_ordinary_fields.py#L478-L491, in this commit: https://github.com/django/django/commit/7cddd8a02e60332c0d02f565c450b0eea0d88438, which is marked as version 1.11. Django version 1.11 was released 11 days ago, see https://github.com/django/django/releases. I suspect that version 1.11 breaks signalserver and that clean installs of signalserver stopped working with that release.

**Comment by ablwr** [comment]
Linked commit acts as hotfix.

**Comment by dericed** [comment]
dedicated to @iamdamosuzuki

**Comment by iamdamosuzuki** [comment]
it works, thanks a bunch!

**Comment by ablwr** [comment]
@iamdamosuzuki is everything working for you now? We've also had some trouble with some javascript not loading.
