### ISSUE TITLE
password reset not working

### ISSUE THREAD

**Issue by lbjohnson01** [bavc/signalserver#231]
Tried testing the ss connection from qctools and got "Error downloading fileuploads/upload/test - server replied: Forbidden" error

Went to reset password and got sent to a 530 error page

![fireshot capture 1 - smtpsenderrefused at _password_rese_ - http___35 161 75 95_8000_password_reset_](https://cloud.githubusercontent.com/assets/9737504/25069286/a4fd687c-2231-11e7-9550-ceedb382bfcd.png)

**Comment by yayoiukai** [comment]
is it on BAVC server? It needs to put email password in settings before you put it on the server. I emailed password to kelly etc. Please let me know if you don't have the password.
