### ISSUE TITLE
mark release

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#236]
we seem to have a ~stable workflow at the moment, should consider marking a release point in github and within the code.

**Comment by ablwr** [comment]
ping~!

**Comment by yayoiukai** [comment]
sorry yes! I will do that. I will cut the release!

**Comment by ablwr** [comment]
yay great!

**Comment by lbjohnson01** [comment]
yes! Congrats!!

____________________

*L.B. Johnson*
Social Media and Digital Content Manager
WordPress Specialist
Creative Technologist

W:       *LBJDigital* <http://lbjdigital.com>
IN:      /lbjohnson01 <http://www.linkedin.com/in/lbjohnson01>
TW:    @LBJDigital <http://www.twitter.com/@LBJDigital>

**Comment by yayoiukai** [comment]
Done. Sorry, it took so long.
