### ISSUE TITLE
add method to download the qctools report

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#237]
I was interested in this for debugging, but I think in general it would be useful to allow a method to get the qctools report back from signalserver.

**Comment by ablwr** [comment]
Can this ticket also encompass uploading reports?

**Comment by yayoiukai** [comment]
It will be nice to have.

**Comment by yayoiukai** [comment]
since we already have uploading function, I changed it to just downloading. Please make another feature request for enhancing current upload function.

**Comment by yayoiukai** [comment]
Added.
