### ISSUE TITLE
simplified 'with-docker' installation process

### ISSUE THREAD

**Issue by bturkus** [bavc/signalserver#238]
fairly self-explanatory, but the signalserver installation process can be tricky for the inexperienced. If there was any way to package the processes (frontend.sh and quickstart.sh), or resolve the cleanup issues internally, I think it would be a great for a lot of us loser users.

**Comment by metacynicv2** [comment]
I got this - I actually spent quite a bit of time already on it a few months ago - table of contents and everything -  but then had some drama with a pull request and ended up deleting it.

**Comment by ablwr** [comment]
Can this be scoped into #250? Closing this more granular issue since we are doing a larger refactoring of docs generally.
