### ISSUE TITLE
Assign group from qcli

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#244]
May also need a sibling ticket in qctools -- users would like to be able to assign groups from qcli.

**Comment by dericed** [comment]
Would you expect that the user simply freetypes a group name or that there's an API call to signalserver to retrieve a list of group name options?

**Comment by ablwr** [comment]
I'm thinking freetype, which seems less complicated to implement, but will suffice.

**Comment by dericed** [comment]
In that case, once @yayoiukai's implements this in the API, then @elderorb can integrate that into qctools/qcli.

**Comment by yayoiukai** [comment]
I will make API for group then.

**Comment by yayoiukai** [comment]
Actually group creation API already exists and it is documented on the readme. Also, you can add file to a specific group from API as well (also documented on README). So maybe this is qctool ticket? Or if I misunderstood, please let me know.
