### ISSUE TITLE
There is no matching data in this policy in this file

### ISSUE THREAD

**Issue by bhavikth** [bavc/signalserver#252]
When I upload a file and then go to the 'Process Group' menu from the 'Files' drop-down menu, I get to see all my groups. When I select any one policy for that particular group say 'TOUT' and click on the 'Process' button, right next to it, I get a list of all the completed requests. When I then click on 'Show Graph' button for any policy in my list, I get the summary as "There is no matching data in this policy in this file". I have also attached a screenshot of the above-mentioned error in the file below. 

![error](https://cloud.githubusercontent.com/assets/22778627/26211904/b9dc95e8-3bc1-11e7-9dd4-30de10684266.png)

This seems to happen for all the policies. So, is it my mistake in entering the rules for the policies or is it due to some other error?

**Comment by yayoiukai** [comment]
Do your group actually have files? This happens when you have a group but the file doesn't exist in the server.

**Comment by bhavikth** [comment]
Yeah, I do have files in my group on the server. Is it possible for you to let me know the steps of uploading the files in the group as I think, I might be missing some step while uploading the files and I feel, it's just that error which is preventing me from moving forward.

**Comment by lbjohnson01** [comment]
following for docs purposes

**Comment by yayoiukai** [comment]
Currently, there are three different ways of making group and it is very likely that some of them are not working very well. 

So these are different ways to make a group. 

1. Upload bunch of file and not selecting any group and select "new group" from drop down list. It will create a group when you upload multiple files at the same time. 
2. Create a group on the file list page (top right side) 
3. Create a group after go to file group page and do a file search and create a group based on the group that you searched. 

I always do #2. Then, I will go to file edit page. (go to group process page and click the group name) and add files one by one. 

Please let me know if you try this way and still doesn't work for you. I will also check the different ways to make a group and make sure it works or I will fix them.

**Comment by bhavikth** [comment]
Okay. Thanks for the above solution.
 
I followed your steps, but when I navigate to "Files->List Files" and when I upload a new file, by clicking on "choose files" option, I see the uploading progress at the bottom left side of the screen but I do not see anything on the "file upload progress bar".

![error1](https://user-images.githubusercontent.com/22778627/27917952-82f4389c-623b-11e7-9bf8-2e3e985f3f24.png)

 The file after it gets uploaded 100%, I am not able to see where that file is. When I head over to "Files->Files Process Status" or to "Files->Process File", I do not see any of my files there. I have attached the screenshots of both the cases below.
 
![error2](https://user-images.githubusercontent.com/22778627/27918094-e905e054-623b-11e7-80a9-cab8b6ed6954.png)

![error3](https://user-images.githubusercontent.com/22778627/27918101-eb564cae-623b-11e7-920d-7364b25fef3f.png)

Any idea on what the error might be or where those files are being saved?

**Comment by yayoiukai** [comment]
It is very strange. Sometimes javascript doesn't load completely some reasons and file upload uses javascript files. Can you run ./frontend.sh and quickstartdev.sh and maybe do quickstart.sh again and see it fixes it? Thank you!

**Comment by yayoiukai** [comment]
You can go to developer tool on chrome. (usually 3 horizontal dots on the right side of the panel. and if you clicks that you will see "more tools" and you can select, developer tools. After you open the developer tools, you can select "console", and you can navigate through page and if you get any javascript error, especially some javascript file is not found, then, it is javascript loading error. If it is the case, please do above (run all ./frontend.sh, and quickstartdev.sh). Please let me know if it helps. Thank you!

**Comment by bhavikth** [comment]
It seems to be working now. I guess there was this JavaScript error because after running the ./frontend.sh, and quickstartdev.sh, it's working. So I guess the JavaScript wasn't able to load completely. Thanks for all the help!!

**Comment by iamdamosuzuki** [comment]
Closing this ticket, thanks for your help Yayoi!
