### ISSUE TITLE
Test issue for tracking training

### ISSUE THREAD

**Issue by iamdamosuzuki** [bavc/signalserver#263]
This is just a test. I'm tagging @lbjohnson01  and @dericed in this. 

I will close this ticket when both users reply that they've seen this

**Comment by dericed** [comment]
... i saw https://github.com/bavc/signalserver/issues/263

**Comment by lbjohnson01** [comment]
I've seen #263

**Comment by iamdamosuzuki** [comment]
hooray! i'm closing out this ticket
