### ISSUE TITLE
index error when trying to load certain pages

### ISSUE THREAD

**Issue by lbjohnson01** [bavc/signalserver#275]
I'm getting an error for File Uploads on . Photo is attached. 

This is from Chrome, but I also get it in Firefox.

**Comment by iamdamosuzuki** [comment]
I am able to access List Files perfectly fine, but am getting a similar error when trying to access "File Process Status"

This is using the  server.

**Comment by yayoiukai** [comment]
I will look into it.

**Comment by yayoiukai** [comment]
should be fixed now. Please let me know if it is still an issue.
