### ISSUE TITLE
fileuploads/list page is really slow. 

### ISSUE THREAD

**Issue by yayoiukai** [bavc/signalserver#279]
Fileuploads/list page is really slow. It needs to speed up.

**Comment by ablwr** [comment]
What's the reason for the slow-slow?

**Comment by yayoiukai** [comment]
Right now it is checking all the status of the group process and file process and generate reports if it is done. I think I need to change a bit how to keep track of the process status and how to generate reports etc. I haven't thought about it but I will work it soon.

**Comment by yayoiukai** [comment]
I disabled some of the status updates for group process and file process. So it should speed up for file page loading now.
