### ISSUE TITLE
Ability to import and export policies

### ISSUE THREAD

**Issue by iamdamosuzuki** [bavc/signalserver#285]
Suggesting a method to import and export policies as XML files. I will work on a mockup of what the XML might look like.

**Comment by iamdamosuzuki** [comment]
Here's a sample of what a policy may look like in XML. The text inside of the element is the description, while all of the other attributes are attributes in the XML object. It doesn't have to be this way, i just thought it might be a good one

```
<?xml version="1.0"?>
<policy type="and" name="Walt Disney Access File">
  <description>8-bit H.264 MP4</description>
  <rule id="1" filter_01="Y HIGH" filter_02="" operation="average" cutoff_number="" dash_group="10.0" dash_file="20.0" dashboard="true">Average of Y HIGH</rule>
  <rule id="2" filter_01="Y MAX" filter_02="" operation="count of frames with value above" cutoff_number="940.0" dash_group="5.0" dash_file="10.0" dashboard="true">Count of the frames with value above 940.0</rule>
  <rule id="3" filter_01="Y HIGH" filter_02="Y LOW" operation="average_difference" cutoff_number="" dash_group="2.0" dash_file="5.0" dashboard="false">Plotting contrast</rule>
</policy>

```

**Comment by yayoiukai** [comment]
I don't have and yet... But it looks good. Thank you!

**Comment by iamdamosuzuki** [comment]
This has been implemented and it looks to be working great! Thanks Yayoi. If I could request one minor tweak: Is it possible for the XML output to be formatted according to standard XML formatting? The following line of code in UNIX does the proper formatting:

xmllint --format policy.xml -o policy.xml

**Comment by yayoiukai** [comment]
okay will do.

**Comment by yayoiukai** [comment]
Done now.
