### ISSUE TITLE
Cannot add rules to a policy

### ISSUE THREAD

**Issue by iamdamosuzuki** [bavc/signalserver#299]
The "add new rules" button within a policy looks like it is being pressed, but does nothing. 

I tried importing a policy using the import function, and this worked. However running files through this policy did not generate any graphs. Not sure if these problems are related. this was built from the source code last updated on Jan 7

**Comment by iamdamosuzuki** [comment]
Update: This may be a problem with either later versions of Chrome/Firefox or Docker. I checked out back to a05aba1b460637482fa476b4179e64cb101a9a43 (Date:   Sun Jul 16 15:20:50 2017 -0700) and am having the same issue

**Comment by dericed** [comment]
Just reporting that I just built from master, ran with quickstart.sh and the latest docker stable release and the policy handling works for me. Testing in chrome 65.

**Comment by dericed** [comment]
also using Docker Version 18.03.0-ce-mac59 (23608)

**Comment by iamdamosuzuki** [comment]
Docker version that I'm having problems with: Version 18.03.0-ce-mac59 (23608)

**Comment by iamdamosuzuki** [comment]
Hrmm, I'm using the same docker version. I'll try again!

**Comment by fr33ky** [comment]
Hi,
I actually have the same problem on a fresh install using docker `Docker version 18.03.0-ce, build 0520e24` and chrome 65, and `quickstart.sh` from master.

Checking `docker-compose logs -f`, we notice the following:
```
web_1     | Not Found: /frontend/bower_components/datetimepicker/jquery.datetimepicker.css
web_1     | [12/Apr/2018 10:22:06] "GET /frontend/bower_components/datetimepicker/jquery.datetimepicker.css HTTP/1.1" 404 1909
web_1     | Not Found: /frontend/bower_components/bootstrap/dist/css/bootstrap.min.css
web_1     | Not Found: /frontend/bower_components/jquery/jquery.min.js
web_1     | [12/Apr/2018 10:22:06] "GET /frontend/bower_components/jquery/jquery.min.js HTTP/1.1" 404 1849
web_1     | [12/Apr/2018 10:22:06] "GET /frontend/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 1897
web_1     | Not Found: /frontend/bower_components/datetimepicker/build/jquery.datetimepicker.full.min.js
web_1     | [12/Apr/2018 10:22:06] "GET /frontend/bower_components/datetimepicker/build/jquery.datetimepicker.full.min.js HTTP/1.1" 404 1951
web_1     | Not Found: /frontend/bower_components/bootstrap/dist/js/bootstrap.min.js
web_1     | [12/Apr/2018 10:22:06] "GET /frontend/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1891
```

I was able to workaround this modifying the `Dockerfile` this way:
```
-COPY ./frontend/bower.json bower.json
-RUN bower install --allow-root
\ No newline at end of file
+RUN cd frontend && bower install --allow-root
```
So `bower_components` directory is built into `frontend`.

I also use private/incognito browsing to ensure there is no cached js files.

**Comment by iamdamosuzuki** [comment]
This worked for me!
