### ISSUE TITLE
Running locally with ./quickstart throws repeating error

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#38]
Here is the warning and error:

WARNING: The FILES_VOLUME_PATH variable is not set. Defaulting to a blank string.
Creating volume "signalserver_dbdata" with default driver
Creating volume "signalserver_files" with default driver
ERROR: create .: volume name invalid: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

**Comment by yayoiukai** [comment]
I will close out this one if that's okay. Since it works on your machine. (FILE_VOLUME_PATH environment variable needs to be set.)
