### ISSUE TITLE
"creation" is spelled "createtion" in configurations

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#43]
An easy fix, hopefully

![picture 2016-09-19 at 11 38 31 am](https://cloud.githubusercontent.com/assets/9436241/18645941/3b02f516-7e64-11e6-8f88-b4257347e477.png)

**Comment by kieranjol** [comment]
Pull request here, hopefully this is all that's needed - https://github.com/bavc/signalserver/pull/45
