### ISSUE TITLE
supply method to edit/reapply evaluation

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#5]
provide a ui so that the user may create, edit, delete, import, export evaluation criteria by selecting from a list of unique metadata keys (BRNG, TOUT, etc) and an operator such as average, count of frames greater than X (or equal to, less than, etc),

**Comment by dericed** [comment]
This is for when files have been evaluated by a configured summarization, but then the summarization's configuration has been updated. So it should be reapplied to existing file data.

**Comment by yayoiukai** [comment]
I think current policy, filter function page does what it is asking here... If it is something else, please let me know.
