### ISSUE TITLE
dynamically add filters to policy test config based on incoming qctools data

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#58]
Presently the dropdowns list frame data from lavfi.cropdetect, lavfi,rebur128, etc, but when new qctools is uploading with new values, the list doesn't update, so it is not possible to make a configuration for metadata from qctools with new values. The filter dropdown on "Add/Delete Filter on Policies" should either update according to supplied data or have some place where the lavfi terms may be registered.

**Comment by yayoiukai** [comment]
Can you tell me where I need to look?

**Comment by dericed** [comment]
In the XML all these values would be in `ffprobe/frame/tag/@key`, such as https://gist.github.com/dericed/56cd478111720393e7bf#file-sample-xml-L16.

**Comment by yayoiukai** [comment]
It seems I have all the filters on this xml files. If you want more, please let me know.
