### ISSUE TITLE
show info and edit ability per rule in policies

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#60]
On the "Add/Delete Filter on Policies" as rules are edited some value doesn't show. For instance if saying that psnr.Y exceeds a cutoff number of 1. The '1' doesn't appear after the rule is supplied. There should be a way to view and edit existing rules of a policy (so far they can only be deleted).

Also Filter2 should only be shown contextually if average-difference is selected, else it has no meaning.

**Comment by yayoiukai** [comment]
display and selection is both fixed.. and updated on server.

**Comment by yayoiukai** [comment]
I noticed that it doesn't work quite well.

**Comment by yayoiukai** [comment]
It is somewhat fixed now. I think.

**Comment by metacynicv2** [comment]
My recent issue is related, I think.

**Comment by yayoiukai** [comment]
Okay i will look more carefully. (I thought it works fine now..) For the meantime, it would be great you can tell me the case things doesn't work as it should.

**Comment by yayoiukai** [comment]
due to no update.
