### ISSUE TITLE
write text for the About page

### ISSUE THREAD

**Issue by dericed** [bavc/signalserver#61]
There's a link to the About page, but it has no where to go. Kelly can you draft some text for an "About" page for SignalServer.

**Comment by dericed** [comment]
File started at https://github.com/bavc/signalserver/blob/master/fileuploads/templates/fileuploads/about.html.

**Comment by ablwr** [comment]
@kellyhaydon if still having trouble, you can send me text and I can add

**Comment by metacynicv2** [comment]
I pushed the About page that I wrote a while back but couldn't update locally.

**Comment by ablwr** [comment]
This has stuff now!
