### ISSUE TITLE
Can a report belong to more than one group?

### ISSUE THREAD

**Issue by ablwr** [bavc/signalserver#92]
Can a report belong to more than one group or is it a 1:1 relationship?

**Comment by dericed** [comment]
My initial impression is that a report belongs to one group. np if it evolves beyond that

**Comment by yayoiukai** [comment]
ya... well. there is a process, which is created by group + policy or file + policy by user request and each process has a result (and this results can be a combination of different results) ... 

So we call that "result" as  "report: for now?

Also, I added another "alert" (or "summary" or "report") based on the results on the process.
