### ISSUE TITLE
Wishlist: window message with status bar while files are uploading

### ISSUE THREAD

**Issue by metacynicv2** [bavc/signalserver#98]
It took several minutes to upload 16 QCtools files. Maybe we could have a window with a fun status bar display while files are uploading? Like this: 

![screen shot 2016-12-08 at 3 35 23 pm](https://cloud.githubusercontent.com/assets/9436241/21032092/fb9002e8-bd5b-11e6-8942-d562555031c8.png)

**Comment by yayoiukai** [comment]
Okay I work on it!

**Comment by ablwr** [comment]
This exists now, right @kellyhaydon? Satisfactory?

**Comment by yayoiukai** [comment]
It exists.. but it is not very good.. (so that's why I didn't close it..)

**Comment by ablwr** [comment]
It exists so let's close this, we can optimize later
